site_name: 全栈 App 开发教程
# Copyright
copyright: 'Copyright &copy; 2018 Wu Jun'
theme:
  name: material
  custom_dir: theme/
  feature:
    tabs: true
extra_css:
  # - assets/stylesheets/material-components-web.min.css
  - assets/stylesheets/mdc-web.css
nav:
    - 教程首页: 'index.md'
 
        
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - smarty:
      smart_quotes: false
  - attr_list
  - def_list
  - tables
  - abbr
  - footnotes
  - codehilite:
       guess_lang: true
  - pymdownx.extrarawhtml:
  - pymdownx.betterem:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences: 
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      user: facelessuser
      repo: pymdown-extensions
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details: